name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  backend-smoke:
    name: Backend smoke check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
          cache-dependency-path: backend/requirements.txt

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Import FastAPI & print versions
        run: python -c "import fastapi, uvicorn; print('fastapi', fastapi.__version__); print('uvicorn', __import__('uvicorn').__version__)"

      # Optional: validate app module is importable
      - name: Import app module
        run: python -c "import importlib; m=importlib.import_module('main'); assert hasattr(m,'app'), 'main.app missing'; print('app found')"
